blank_issues_enabled: false
contact_links:
  - name: ✨ Feature Requests
    url: https://request.apolloreborn.app/
    about: Submit new feature requests and vote on existing ideas.
  - name: 💬 r/ApolloReborn Community
    url: https://www.reddit.com/r/ApolloReborn/
    about: Ask questions, get help, and discuss with the community. (Do not directly discuss API key workarounds using alternative apps in this subreddit.)
