#!/usr/bin/env python3
from __future__ import annotations

import html
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
CONFIG_PATH = ROOT / "contributors.json"

START_MARKER = "<!-- CONTRIBUTORS-LIST:START"
END_MARKER = "<!-- CONTRIBUTORS-LIST:END -->"

ROLE_LABELS = {
    "code": "Code Contributors",
    "design": "Icon & Design Contributors",
}

ROLE_BADGES = {
    "maintainer": ("Maintainer", "Maintainer"),
    "code": ("Code", "Code"),
    "design": ("Design", "Icon and design"),
}

DESIGN_CREDIT_URL = "https://github.com/Apollo-Reborn/Apollo-Reborn/tree/main/liquid-glass#bundled-icons"


def load_config() -> dict:
    return json.loads(CONFIG_PATH.read_text())


def gh_user(login: str) -> dict:
    proc = subprocess.run(
        ["gh", "api", f"users/{login}"],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"gh api users/{login} failed:\n{proc.stderr.strip()}")
    return json.loads(proc.stdout)


def contributor_id(entry: dict) -> str:
    return entry.get("github") or entry.get("id") or entry.get("displayName") or entry.get("profileUrl")


def enrich(entry: dict) -> dict:
    result = dict(entry)
    login = result.get("github")
    if login:
        user = gh_user(login)
        result["displayName"] = user.get("login") or login
        result["avatarUrl"] = user.get("avatar_url")
        result["profileUrl"] = user.get("html_url") or f"https://github.com/{login}"
    else:
        result.setdefault("displayName", result.get("id"))

    missing = [key for key in ("role", "displayName") if not result.get(key)]
    if missing:
        ident = contributor_id(entry) or "<unknown>"
        raise ValueError(f"Contributor {ident} is missing required field(s): {', '.join(missing)}")
    if result["role"] not in ROLE_BADGES:
        ident = contributor_id(entry) or result["displayName"]
        raise ValueError(f"Contributor {ident} has unsupported role: {result['role']}")
    return result


def avatar_url(url: str | None) -> str | None:
    if not url:
        return None
    separator = "&" if "?" in url else "?"
    return f"{url}{separator}s=100"


def render_cell(contributor: dict, repo: str, width: str) -> str:
    name = html.escape(contributor["displayName"])
    profile = contributor.get("profileUrl")
    avatar = avatar_url(contributor.get("avatarUrl"))
    role = contributor["role"]
    badge_label, badge_title = ROLE_BADGES[role]

    if role == "code" and contributor.get("github"):
        badge_href = f"https://github.com/{repo}/commits?author={contributor['github']}"
    elif role == "design":
        badge_href = DESIGN_CREDIT_URL
    else:
        badge_href = f"#{role}-{contributor_id(contributor)}"

    parts = []
    if avatar:
        image = (
            f'<img src="{html.escape(avatar)}" width="100px;" height="100px;" '
            f'style="object-fit: cover;" alt="{name}"/>'
        )
        if profile:
            image = f'<a href="{html.escape(profile)}">{image}</a>'
        parts.append(image)
    parts.append(f"<sub><b>{name}</b></sub>")

    badge_link = (
        f'<a href="{html.escape(badge_href)}" title="{html.escape(badge_title)}">'
        f"{html.escape(badge_label)}</a>"
    )
    bmc_url = contributor.get("buyMeACoffeeUrl")
    if bmc_url:
        badge_link += (
            f'<br /><a href="{html.escape(bmc_url)}" title="Buy Me a Coffee">☕</a>'
        )

    return (
        f'      <td align="center" valign="top" width="{width}">'
        f'{"<br />".join(parts)}<br />{badge_link}</td>'
    )


def render_table(contributors: list[dict], repo: str, per_row: int) -> list[str]:
    width = f"{100 / per_row:.2f}%"
    lines = ["<table>", "  <tbody>"]
    for index in range(0, len(contributors), per_row):
        lines.append("    <tr>")
        for contributor in contributors[index : index + per_row]:
            lines.append(render_cell(contributor, repo, width))
        lines.append("    </tr>")
    lines.extend(["  </tbody>", "</table>"])
    return lines


def render_block(config: dict, contributors: list[dict]) -> str:
    repo = config["repo"]
    per_row = int(config.get("contributorsPerRow", 7))
    lines = [
        "<!-- CONTRIBUTORS-LIST:START - Generated by .agents/skills/update-contributors/generate-readme-contributors.py -->",
    ]

    groups = [
        ("code", [contributor for contributor in contributors if contributor["role"] in ("maintainer", "code")]),
        ("design", [contributor for contributor in contributors if contributor["role"] == "design"]),
    ]
    for label_role, group in groups:
        if not group:
            continue
        lines.extend(["", f"### {ROLE_LABELS[label_role]}", ""])
        lines.extend(render_table(group, repo, per_row))

    lines.extend(
        [
            "",
            END_MARKER,
        ]
    )
    return "\n".join(lines)


def replace_between_markers(readme: str, block: str) -> str:
    start = readme.find(START_MARKER)
    if start == -1:
        raise ValueError(f"Could not find {START_MARKER} in README")
    end = readme.find(END_MARKER, start)
    if end == -1:
        raise ValueError(f"Could not find {END_MARKER} in README")
    end += len(END_MARKER)
    return readme[:start] + block + readme[end:]


def main() -> int:
    config = load_config()
    contributors = [enrich(entry) for entry in config["contributors"]]
    readme_path = ROOT / config.get("readme", "README.md")
    readme = readme_path.read_text()
    updated = replace_between_markers(readme, render_block(config, contributors))
    readme_path.write_text(updated)
    print(f"Updated {readme_path.relative_to(ROOT)} from {CONFIG_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
