#!/usr/bin/env python3
import json
import sys
from pathlib import Path


def fail(path, message):
    label = str(path) if path else "catalog"
    raise SystemExit(f"{label}: {message}")


def c_string(value):
    parts = []
    for byte in value.encode("utf-8"):
        if byte == 0x5C:
            parts.append("\\\\")
        elif byte == 0x22:
            parts.append('\\"')
        elif 0x20 <= byte <= 0x7E:
            parts.append(chr(byte))
        else:
            parts.append(f"\\{byte:03o}")
    return '"' + "".join(parts) + '"'


def non_empty_string(obj, key, path):
    value = obj.get(key)
    if not isinstance(value, str) or not value.strip():
        fail(path, f"{key} must be a non-empty string")
    return value


def load_release(path):
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        fail(path, f"invalid JSON: {exc}")

    if data.get("schemaVersion") != 1:
        fail(path, "schemaVersion must be 1")

    version = non_empty_string(data, "version", path)
    if version != path.stem:
        fail(path, f"version must match filename stem ({path.stem})")

    headline = non_empty_string(data, "headline", path)

    items = data.get("items")
    if not isinstance(items, list) or not items:
        fail(path, "items must be a non-empty array")

    parsed_items = []
    for item in items:
        if not isinstance(item, dict):
            fail(path, "each item must be an object")
        parsed_items.append({
            "icon": non_empty_string(item, "icon", path),
            "title": non_empty_string(item, "title", path),
            "subtitle": non_empty_string(item, "subtitle", path),
        })

    return {"version": version, "headline": headline, "items": parsed_items}


def emit_header(path):
    path.write_text("""// Generated by whats-new/scripts/generate_catalog.py. Do not edit.
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

// Wrapped in extern "C" so the ObjC++ (.xm) caller (ApolloWhatsNew.xm) and this
// ObjC (.m) definition agree on the unmangled symbol name — see the identical
// note on ApolloSanitizedHoldSpeed in ApolloState.h.
#ifdef __cplusplus
extern "C" {
#endif

// Returns @{ @"headline": NSString, @"items": @[ @{ @"icon", @"title", @"subtitle" }, ... ] }
// for the given tweak version, or nil if that version has no What's New content.
NSDictionary *_Nullable ApolloWhatsNewCatalogGeneratedReleaseForVersion(NSString *version);

#ifdef __cplusplus
}
#endif

NS_ASSUME_NONNULL_END
""")


def emit_implementation(path, releases):
    lines = [
        "// Generated by whats-new/scripts/generate_catalog.py. Do not edit.",
        '#import "ApolloWhatsNewCatalog.gen.h"',
        "",
        "typedef struct {",
        "    const char *version;",
        "    const char *headline;",
        "} ApolloWhatsNewReleaseEntry;",
        "",
        "typedef struct {",
        "    const char *version;",
        "    const char *icon;",
        "    const char *title;",
        "    const char *subtitle;",
        "} ApolloWhatsNewItemEntry;",
        "",
        "static const ApolloWhatsNewReleaseEntry kWhatsNewReleases[] = {",
    ]
    for release in releases:
        encoded = ", ".join(c_string(v) for v in (release["version"], release["headline"]))
        lines.append(f"    {{ {encoded} }},")
    lines.extend([
        "};",
        "",
        "static const ApolloWhatsNewItemEntry kWhatsNewItems[] = {",
    ])
    for release in releases:
        for item in release["items"]:
            encoded = ", ".join(
                c_string(v) for v in (release["version"], item["icon"], item["title"], item["subtitle"])
            )
            lines.append(f"    {{ {encoded} }},")
    lines.extend([
        "};",
        "",
        "static NSString *S(const char *value) { return [NSString stringWithUTF8String:value]; }",
        "",
        "NSDictionary *ApolloWhatsNewCatalogGeneratedReleaseForVersion(NSString *version) {",
        "    if (version.length == 0) return nil;",
        "",
        "    const char *headline = NULL;",
        "    for (NSUInteger i = 0; i < sizeof(kWhatsNewReleases) / sizeof(kWhatsNewReleases[0]); i++) {",
        "        if ([version isEqualToString:S(kWhatsNewReleases[i].version)]) {",
        "            headline = kWhatsNewReleases[i].headline;",
        "            break;",
        "        }",
        "    }",
        "    if (!headline) return nil;",
        "",
        "    NSMutableArray<NSDictionary *> *items = [NSMutableArray array];",
        "    for (NSUInteger i = 0; i < sizeof(kWhatsNewItems) / sizeof(kWhatsNewItems[0]); i++) {",
        "        const ApolloWhatsNewItemEntry *entry = &kWhatsNewItems[i];",
        "        if ([version isEqualToString:S(entry->version)]) {",
        "            [items addObject:@{",
        '                @"icon": S(entry->icon),',
        '                @"title": S(entry->title),',
        '                @"subtitle": S(entry->subtitle),',
        "            }];",
        "        }",
        "    }",
        "    if (items.count == 0) return nil;",
        "",
        '    return @{ @"headline": S(headline), @"items": [items copy] };',
        "}",
        "",
    ])
    path.write_text("\n".join(lines))


def main(argv):
    if len(argv) != 4:
        raise SystemExit("usage: generate_catalog.py <releases-dir> <out-header> <out-impl>")
    releases_dir = Path(argv[1])
    out_header = Path(argv[2])
    out_impl = Path(argv[3])
    paths = sorted(releases_dir.glob("*.json"))
    if not paths:
        fail(releases_dir, "no release JSON files found")
    releases = [load_release(path) for path in paths]
    seen = set()
    for release in releases:
        if release["version"] in seen:
            fail(None, f"duplicate version {release['version']}")
        seen.add(release["version"])
    out_header.parent.mkdir(parents=True, exist_ok=True)
    out_impl.parent.mkdir(parents=True, exist_ok=True)
    emit_header(out_header)
    emit_implementation(out_impl, releases)
    print(f"generated {len(releases)} what's new releases")


if __name__ == "__main__":
    main(sys.argv)
