#!/usr/bin/env python3
"""Generate src/settings/ApolloSettingsSearchNativeIndex.h from a settings crawl dump.

The dump is an NDJSON produced by the in-sim settings crawler (one JSON object
per visited screen: {path, title, class, sections:[{header, rows:[{title,
accessory, ...}]}]}). This emits a static ObjC table of native rows for
settings search: title, breadcrumb context, the label path to tap through from
the Settings root, and whether selecting the row pushes a screen (disclosure)
or just gets scrolled to and flashed.

Rows owned by the tweak (the Reborn section, Theme Manager, Buy Us a Coffee)
are excluded — the search index covers those live via the route registry, so
they stay in sync with the tweak instead of a crawl snapshot.

Usage: gen-settings-search-index.py <native-dump.ndjson> <output.h>
"""

import json
import sys

# Screens/rows the tweak owns (covered by the live Reborn index instead).
TWEAK_ROW_TITLES = {
    "Buy Us a Coffee",
    "Apollo Reborn",
    "Saved Categories",
    "Translation",
    "Tag Filters",
    "Picture-in-Picture",
    "Theme Manager",
}


def objc_str(s: str) -> str:
    return '@"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(dump_path: str, out_path: str) -> None:
    screens = []
    for line in open(dump_path):
        d = json.loads(line)
        path = d.get("path") or ""
        if not path.startswith("Settings") or "(modal)" in path:
            continue
        if "sections" not in d:
            continue
        components = [c.strip() for c in path.split("→")]
        # components[0] == "Settings"; the rest are the row labels tapped.
        hops = components[1:]
        if any(h.startswith("row ") for h in hops):  # crawler couldn't title the hop
            continue
        if any(h in TWEAK_ROW_TITLES for h in hops):
            continue
        screens.append((hops, d))

    entries = []
    for hops, d in screens:
        for section in d["sections"]:
            header = (section.get("header") or "").strip()
            crumb = " → ".join(hops) if hops else "Settings"
            if header:
                crumb = f"{crumb} → {header}" if hops else header
            for row in section.get("rows", []):
                title = (row.get("title") or "").strip()
                if not title or title in TWEAK_ROW_TITLES:
                    continue
                if not hops and title == "Buy Us a Coffee":
                    continue
                pushes = row.get("accessory") == "disclosure"
                entries.append((title, crumb, "|".join(hops), pushes))

    with open(out_path, "w") as f:
        f.write(
            "// GENERATED by scripts/gen-settings-search-index.py from an in-sim\n"
            "// settings crawl dump — do not hand-edit; re-run the crawler + generator\n"
            "// after a base-IPA bump instead. Each entry is\n"
            "//   @[ title, breadcrumb, tap-path (\"|\"-joined row labels from the\n"
            "//      Settings root; empty = the root itself), @(pushesScreen) ]\n"
            "// Selection is resolved at runtime by LABEL MATCHING, never by stored\n"
            "// index paths, so entries fail soft when Apollo moves a row.\n\n"
            "#import <Foundation/Foundation.h>\n\n"
            "static NSArray<NSArray *> *ApolloSettingsSearchNativeRows(void) {\n"
            "    static NSArray<NSArray *> *rows;\n"
            "    static dispatch_once_t onceToken;\n"
            "    dispatch_once(&onceToken, ^{\n"
            "        rows = @[\n"
        )
        for title, crumb, path, pushes in entries:
            f.write(
                f"            @[{objc_str(title)}, {objc_str(crumb)}, "
                f"{objc_str(path)}, @{'YES' if pushes else 'NO'}],\n"
            )
        f.write("        ];\n    });\n    return rows;\n}\n")

    print(f"{len(entries)} native entries -> {out_path}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
