#!/usr/bin/env python3
"""Generate the compiled allowlist for repository-hosted Bark icon PNGs."""

from __future__ import annotations

import argparse
from pathlib import Path


def render(icon_directory: Path) -> str:
    names = sorted(path.stem for path in icon_directory.glob("*.png") if path.is_file())
    if "default" not in names:
        raise SystemExit(f"error: {icon_directory / 'default.png'} is missing")
    if not names:
        raise SystemExit(f"error: no PNG icons found in {icon_directory}")

    entries = "\n".join(f'    @"{name}",' for name in names)
    return f"""// Generated by scripts/generate-bark-icon-names.py. Do not edit.
#pragma once

static NSString *const ApolloBarkHostedIconNameList[] = {{
{entries}
}};

static const NSUInteger ApolloBarkHostedIconNameCount =
    sizeof(ApolloBarkHostedIconNameList) / sizeof(ApolloBarkHostedIconNameList[0]);
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("icon_directory", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = render(args.icon_directory)
    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != generated:
            raise SystemExit(f"error: {args.output} is stale; regenerate it")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
