#import "ApolloClasses.h"
#import <objc/runtime.h>
#include <stdatomic.h>

Class ApolloClassASBackgroundLayoutSpec;
Class ApolloClassASButtonNode;
Class ApolloClassASCellNode;
Class ApolloClassASCenterLayoutSpec;
Class ApolloClassASCollectionView;
Class ApolloClassASControlNode;
Class ApolloClassASDisplayNode;
Class ApolloClassASEditableTextNode;
Class ApolloClassASImageNode;
Class ApolloClassASInsetLayoutSpec;
Class ApolloClassASLayout;
Class ApolloClassASLayoutSpec;
Class ApolloClassASNetworkImageNode;
Class ApolloClassASRatioLayoutSpec;
Class ApolloClassASStackLayoutSpec;
Class ApolloClassASTableNode;
Class ApolloClassASTableView;
Class ApolloClassASTableViewController;
Class ApolloClassASTextNode;
Class ApolloClassASTextNode2;
Class ApolloClassAccountManager;
Class ApolloClassActionController;
Class ApolloClassApolloContentBridge;
Class ApolloClassApolloDefaultTableViewCell;
Class ApolloClassApolloFeedGalleryCarouselView;
Class ApolloClassApolloFoundationModels;
Class ApolloClassApolloNavigationAnimator;
Class ApolloClassApolloNavigationController;
Class ApolloClassApolloOnscreenBridge;
Class ApolloClassApolloProfileHeaderView;
Class ApolloClassApolloProfileNavTitleView;
Class ApolloClassApolloSearchBarTextField;
Class ApolloClassApolloSettingsShortcutsViewController;
Class ApolloClassApolloSubredditHeaderWrapperView;
Class ApolloClassApolloSubtitleTableViewCell;
Class ApolloClassApolloTableViewController;
Class ApolloClassCAFilter;
Class ApolloClassCommentCellNode;
Class ApolloClassCommentsHeaderCellNode;
Class ApolloClassCommentsHeaderSectionController;
Class ApolloClassCommentsViewController;
Class ApolloClassCompactPostCellNode;
Class ApolloClassComposePostViewController;
Class ApolloClassComposeViewController;
Class ApolloClassCrosspostPerformViewController;
Class ApolloClassDualStateButtonNode;
Class ApolloClassFLAnimatedImage;
Class ApolloClassFLAnimatedImageView;
Class ApolloClassJumpBar;
Class ApolloClassLGFeaturedStripCell;
Class ApolloClassLGPackGridRowCell;
Class ApolloClassLargePostCellNode;
Class ApolloClassLinkButtonNode;
Class ApolloClassMFMailComposeViewController;
Class ApolloClassMFMessageComposeViewController;
Class ApolloClassMarkdownNode;
Class ApolloClassMarkdownTextNode;
Class ApolloClassMediaPageViewController;
Class ApolloClassMediaViewerController;
Class ApolloClassMediaViewerPresentationController;
Class ApolloClassModeratorReportsController;
Class ApolloClassModmailInboxViewController;
Class ApolloClassPixelPalAddedSceneElementImageView;
Class ApolloClassPixelPalOverlayViewController;
Class ApolloClassPlayerLayerContainerView;
Class ApolloClassPollNode;
Class ApolloClassPollOptionNode;
Class ApolloClassPollResultNode;
Class ApolloClassPostInfoNode;
Class ApolloClassPostsSearchResultsViewController;
Class ApolloClassPostsViewController;
Class ApolloClassProfileFeatureCellNode;
Class ApolloClassProfileViewController;
Class ApolloClassRDKClient;
Class ApolloClassRDKComment;
Class ApolloClassRDKFlair;
Class ApolloClassRDKFlairOption;
Class ApolloClassRDKGallery;
Class ApolloClassRDKGalleryItemImage;
Class ApolloClassRDKLink;
Class ApolloClassRDKMessage;
Class ApolloClassRDKMultireddit;
Class ApolloClassRDKMultiredditDescription;
Class ApolloClassRDKObjectBuilder;
Class ApolloClassRDKSubreddit;
Class ApolloClassRecreatedTableSectionHeaderView;
Class ApolloClassRedditListTableViewCell;
Class ApolloClassRedditListViewController;
Class ApolloClassRichMediaNode;
Class ApolloClassSaveMediaActivity;
Class ApolloClassSearchViewController;
Class ApolloClassSettingsViewController;
Class ApolloClassShareAsImageViewController;
Class ApolloClassSubItemTableViewCell;
Class ApolloClassThickSeparatorCellNode;
Class ApolloClassThinSeparatorCellNode;
Class ApolloClassTranslatorViewController;
Class ApolloClassUIBarBadgeView;
Class ApolloClassUIButtonLabel;
Class ApolloClassUIContextMenuListView;
Class ApolloClassUIContextMenuPlatformMetricsGlass;
Class ApolloClassUIContinuousSelectionGestureRecognizer;
Class ApolloClassUICornerConfiguration;
Class ApolloClassUIDropShadowView;
Class ApolloClassUIFloatingTabBarSelectionContainerView;
Class ApolloClassUIGlassEffect;
Class ApolloClassUIKBKeyView;
Class ApolloClassUIKBVisualEffectView;
Class ApolloClassUINavigationBarHostedViewContainer;
Class ApolloClassUINavigationBarPlatterGlassView;
Class ApolloClassUINavigationBarPlatterView;
Class ApolloClassUINavigationBarTitleControl;
Class ApolloClassUIScrollEdgeEffectStyle;
Class ApolloClassUserCommentsViewController;

// Bumped once per image ObjC finishes mapping (and once per image already
// loaded when the callback is registered). Lazy accessors for classes that may
// never exist compare against it so they only retry after something new loads.
static _Atomic(uint32_t) sLoadedImageGeneration;

static void ApolloClassesImageLoaded(const struct mach_header *header) {
    // Runs with ObjC's runtime lock held: no ObjC calls (objc_getClass would
    // deadlock), just note that the set of loaded classes may have grown.
    (void)header;
    atomic_fetch_add_explicit(&sLoadedImageGeneration, 1, memory_order_release);
}

__attribute__((constructor)) static void ApolloClassesResolve(void) {
    objc_addLoadImageFunc(ApolloClassesImageLoaded);
    ApolloClassASBackgroundLayoutSpec = objc_getClass("ASBackgroundLayoutSpec");
    ApolloClassASButtonNode = objc_getClass("ASButtonNode");
    ApolloClassASCellNode = objc_getClass("ASCellNode");
    ApolloClassASCenterLayoutSpec = objc_getClass("ASCenterLayoutSpec");
    ApolloClassASCollectionView = objc_getClass("ASCollectionView");
    ApolloClassASControlNode = objc_getClass("ASControlNode");
    ApolloClassASDisplayNode = objc_getClass("ASDisplayNode");
    ApolloClassASEditableTextNode = objc_getClass("ASEditableTextNode");
    ApolloClassASImageNode = objc_getClass("ASImageNode");
    ApolloClassASInsetLayoutSpec = objc_getClass("ASInsetLayoutSpec");
    ApolloClassASLayout = objc_getClass("ASLayout");
    ApolloClassASLayoutSpec = objc_getClass("ASLayoutSpec");
    ApolloClassASNetworkImageNode = objc_getClass("ASNetworkImageNode");
    ApolloClassASRatioLayoutSpec = objc_getClass("ASRatioLayoutSpec");
    ApolloClassASStackLayoutSpec = objc_getClass("ASStackLayoutSpec");
    ApolloClassASTableNode = objc_getClass("ASTableNode");
    ApolloClassASTableView = objc_getClass("ASTableView");
    ApolloClassASTableViewController = objc_getClass("_TtC6Apollo21ASTableViewController");
    ApolloClassASTextNode = objc_getClass("ASTextNode");
    ApolloClassASTextNode2 = objc_getClass("ASTextNode2");
    ApolloClassAccountManager = objc_getClass("_TtC6Apollo14AccountManager");
    ApolloClassActionController = objc_getClass("_TtC6Apollo16ActionController");
    ApolloClassApolloContentBridge = objc_getClass("ApolloContentBridge");
    ApolloClassApolloDefaultTableViewCell = objc_getClass("_TtC6Apollo26ApolloDefaultTableViewCell");
    ApolloClassApolloFeedGalleryCarouselView = objc_getClass("ApolloFeedGalleryCarouselView");
    ApolloClassApolloFoundationModels = objc_getClass("ApolloFoundationModels");
    ApolloClassApolloNavigationAnimator = objc_getClass("_TtC6Apollo24ApolloNavigationAnimator");
    ApolloClassApolloNavigationController = objc_getClass("_TtC6Apollo26ApolloNavigationController");
    ApolloClassApolloOnscreenBridge = objc_getClass("ApolloOnscreenBridge");
    ApolloClassApolloProfileHeaderView = objc_getClass("ApolloProfileHeaderView");
    ApolloClassApolloProfileNavTitleView = objc_getClass("ApolloProfileNavTitleView");
    ApolloClassApolloSearchBarTextField = objc_getClass("_TtC6Apollo24ApolloSearchBarTextField");
    ApolloClassApolloSettingsShortcutsViewController = objc_getClass("ApolloSettingsShortcutsViewController");
    ApolloClassApolloSubredditHeaderWrapperView = objc_getClass("ApolloSubredditHeaderWrapperView");
    ApolloClassApolloSubtitleTableViewCell = objc_getClass("_TtC6Apollo27ApolloSubtitleTableViewCell");
    ApolloClassApolloTableViewController = objc_getClass("_TtC6Apollo25ApolloTableViewController");
    ApolloClassCAFilter = objc_getClass("CAFilter");
    ApolloClassCommentCellNode = objc_getClass("_TtC6Apollo15CommentCellNode");
    ApolloClassCommentsHeaderCellNode = objc_getClass("_TtC6Apollo22CommentsHeaderCellNode");
    ApolloClassCommentsHeaderSectionController = objc_getClass("_TtC6Apollo31CommentsHeaderSectionController");
    ApolloClassCommentsViewController = objc_getClass("_TtC6Apollo22CommentsViewController");
    ApolloClassCompactPostCellNode = objc_getClass("_TtC6Apollo19CompactPostCellNode");
    ApolloClassComposePostViewController = objc_getClass("_TtC6Apollo25ComposePostViewController");
    ApolloClassComposeViewController = objc_getClass("_TtC6Apollo21ComposeViewController");
    ApolloClassCrosspostPerformViewController = objc_getClass("_TtC6Apollo30CrosspostPerformViewController");
    ApolloClassDualStateButtonNode = objc_getClass("_TtC6Apollo19DualStateButtonNode");
    ApolloClassFLAnimatedImage = objc_getClass("FLAnimatedImage");
    ApolloClassFLAnimatedImageView = objc_getClass("FLAnimatedImageView");
    ApolloClassJumpBar = objc_getClass("_TtC6Apollo7JumpBar");
    ApolloClassLGFeaturedStripCell = objc_getClass("LGFeaturedStripCell");
    ApolloClassLGPackGridRowCell = objc_getClass("LGPackGridRowCell");
    ApolloClassLargePostCellNode = objc_getClass("_TtC6Apollo17LargePostCellNode");
    ApolloClassLinkButtonNode = objc_getClass("_TtC6Apollo14LinkButtonNode");
    ApolloClassMFMailComposeViewController = objc_getClass("MFMailComposeViewController");
    ApolloClassMFMessageComposeViewController = objc_getClass("MFMessageComposeViewController");
    ApolloClassMarkdownNode = objc_getClass("_TtC6Apollo12MarkdownNode");
    ApolloClassMarkdownTextNode = objc_getClass("_TtC6Apollo16MarkdownTextNode");
    ApolloClassMediaPageViewController = objc_getClass("_TtC6Apollo23MediaPageViewController");
    ApolloClassMediaViewerController = objc_getClass("_TtC6Apollo21MediaViewerController");
    ApolloClassMediaViewerPresentationController = objc_getClass("_TtC6Apollo33MediaViewerPresentationController");
    ApolloClassModeratorReportsController = objc_getClass("_TtC6Apollo26ModeratorReportsController");
    ApolloClassModmailInboxViewController = objc_getClass("_TtC6Apollo26ModmailInboxViewController");
    ApolloClassPixelPalAddedSceneElementImageView = objc_getClass("_TtC6Apollo34PixelPalAddedSceneElementImageView");
    ApolloClassPixelPalOverlayViewController = objc_getClass("_TtC6Apollo29PixelPalOverlayViewController");
    ApolloClassPlayerLayerContainerView = objc_getClass("_TtC6Apollo24PlayerLayerContainerView");
    ApolloClassPollNode = objc_getClass("_TtC6Apollo8PollNode");
    ApolloClassPollOptionNode = objc_getClass("_TtC6Apollo14PollOptionNode");
    ApolloClassPollResultNode = objc_getClass("_TtC6Apollo14PollResultNode");
    ApolloClassPostInfoNode = objc_getClass("_TtC6Apollo12PostInfoNode");
    ApolloClassPostsSearchResultsViewController = objc_getClass("_TtC6Apollo32PostsSearchResultsViewController");
    ApolloClassPostsViewController = objc_getClass("_TtC6Apollo19PostsViewController");
    ApolloClassProfileFeatureCellNode = objc_getClass("_TtC6Apollo22ProfileFeatureCellNode");
    ApolloClassProfileViewController = objc_getClass("_TtC6Apollo21ProfileViewController");
    ApolloClassRDKClient = objc_getClass("RDKClient");
    ApolloClassRDKComment = objc_getClass("RDKComment");
    ApolloClassRDKFlair = objc_getClass("RDKFlair");
    ApolloClassRDKFlairOption = objc_getClass("RDKFlairOption");
    ApolloClassRDKGallery = objc_getClass("RDKGallery");
    ApolloClassRDKGalleryItemImage = objc_getClass("RDKGalleryItemImage");
    ApolloClassRDKLink = objc_getClass("RDKLink");
    ApolloClassRDKMessage = objc_getClass("RDKMessage");
    ApolloClassRDKMultireddit = objc_getClass("RDKMultireddit");
    ApolloClassRDKMultiredditDescription = objc_getClass("RDKMultiredditDescription");
    ApolloClassRDKObjectBuilder = objc_getClass("RDKObjectBuilder");
    ApolloClassRDKSubreddit = objc_getClass("RDKSubreddit");
    ApolloClassRecreatedTableSectionHeaderView = objc_getClass("_TtC6Apollo31RecreatedTableSectionHeaderView");
    ApolloClassRedditListTableViewCell = objc_getClass("_TtC6Apollo23RedditListTableViewCell");
    ApolloClassRedditListViewController = objc_getClass("_TtC6Apollo24RedditListViewController");
    ApolloClassRichMediaNode = objc_getClass("_TtC6Apollo13RichMediaNode");
    ApolloClassSaveMediaActivity = objc_getClass("_TtC6Apollo17SaveMediaActivity");
    ApolloClassSearchViewController = objc_getClass("_TtC6Apollo20SearchViewController");
    ApolloClassSettingsViewController = objc_getClass("_TtC6Apollo22SettingsViewController");
    ApolloClassShareAsImageViewController = objc_getClass("_TtC6Apollo26ShareAsImageViewController");
    ApolloClassSubItemTableViewCell = objc_getClass("_TtC6Apollo20SubItemTableViewCell");
    ApolloClassThickSeparatorCellNode = objc_getClass("_TtC6Apollo22ThickSeparatorCellNode");
    ApolloClassThinSeparatorCellNode = objc_getClass("_TtC6Apollo21ThinSeparatorCellNode");
    ApolloClassTranslatorViewController = objc_getClass("_TtC6Apollo24TranslatorViewController");
    ApolloClassUIBarBadgeView = objc_getClass("_UIBarBadgeView");
    ApolloClassUIButtonLabel = objc_getClass("UIButtonLabel");
    ApolloClassUIContextMenuListView = objc_getClass("_UIContextMenuListView");
    ApolloClassUIContextMenuPlatformMetricsGlass = objc_getClass("_UIContextMenuPlatformMetrics_Glass");
    ApolloClassUIContinuousSelectionGestureRecognizer = objc_getClass("_UIContinuousSelectionGestureRecognizer");
    ApolloClassUICornerConfiguration = objc_getClass("UICornerConfiguration");
    ApolloClassUIDropShadowView = objc_getClass("UIDropShadowView");
    ApolloClassUIFloatingTabBarSelectionContainerView = objc_getClass("_UIFloatingTabBarSelectionContainerView");
    ApolloClassUIGlassEffect = objc_getClass("UIGlassEffect");
    ApolloClassUIKBKeyView = objc_getClass("UIKBKeyView");
    ApolloClassUIKBVisualEffectView = objc_getClass("UIKBVisualEffectView");
    ApolloClassUINavigationBarHostedViewContainer = objc_getClass("_UINavigationBarHostedViewContainer");
    ApolloClassUINavigationBarPlatterGlassView = objc_getClass("_UINavigationBarPlatterGlassView");
    ApolloClassUINavigationBarPlatterView = objc_getClass("_UINavigationBarPlatterView");
    ApolloClassUINavigationBarTitleControl = objc_getClass("_UINavigationBarTitleControl");
    ApolloClassUIScrollEdgeEffectStyle = objc_getClass("UIScrollEdgeEffectStyle");
    ApolloClassUserCommentsViewController = objc_getClass("_TtC6Apollo26UserCommentsViewController");
}

Class ApolloTUIVariantSelectorViewClass(void) {
    static _Atomic(void *) cached;
    void *p = atomic_load_explicit(&cached, memory_order_acquire);
    if (!p) {
        p = (__bridge void *)objc_getClass("TUIVariantSelectorView");
        if (p) atomic_store_explicit(&cached, p, memory_order_release);
    }
    return (__bridge Class)p;
}

Class ApolloSLComposeViewControllerClass(void) {
    static _Atomic(void *) cached;
    static _Atomic(uint32_t) missedAtGeneration;
    void *p = atomic_load_explicit(&cached, memory_order_acquire);
    if (p) return (__bridge Class)p;
    // Nothing has loaded since the last miss, so the class still can't exist.
    uint32_t generation = atomic_load_explicit(&sLoadedImageGeneration, memory_order_acquire);
    if (generation == atomic_load_explicit(&missedAtGeneration, memory_order_relaxed)) return Nil;
    p = (__bridge void *)objc_getClass("SLComposeViewController");
    if (p) atomic_store_explicit(&cached, p, memory_order_release);
    else atomic_store_explicit(&missedAtGeneration, generation, memory_order_relaxed);
    return (__bridge Class)p;
}
