// ApolloBadgeBookCatalog.{h,m}
//
// The "Badge Book" is a profile-attached view of a redditor's collectibles:
//   • Achievements — Reddit's current badge system (earned + locked catalogue)
//   • Trophy Case  — the legacy trophies shown on a profile
//
// This file loads the BUNDLED display catalogue that ships inside
// ApolloReborn.bundle (generated by scripts/badgebook-assets.mjs from the
// extracted Reddit catalogues). Bundling the metadata + downscaled icons means
// the achievements book renders instantly and fully offline — no per-view
// network round-trip for names, descriptions, categories, or images. Per-user
// "which of these did they earn" is resolved separately by ApolloBadgeBookScraper.
//
// Live / uncatalogued trophies (Reddit issues one-off and subreddit trophies we
// can't pre-bundle) keep their remote image_url so they still render.

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, ApolloBadgeKind) {
    ApolloBadgeKindAchievement = 0,
    ApolloBadgeKindTrophy = 1,
};

// One collectible: an achievement (with a category) or a trophy.
@interface ApolloBadgeItem : NSObject
@property(nonatomic) ApolloBadgeKind kind;
@property(nonatomic, copy) NSString *identifier;
@property(nonatomic, copy) NSString *title;
@property(nonatomic, copy, nullable) NSString *bio;
@property(nonatomic, copy, nullable) NSString *category;             // achievements only
@property(nonatomic, copy, nullable) NSString *imageFile;            // bundled filename (a_*/t_*.png), nil if not bundled
@property(nonatomic, copy, nullable) NSString *imageURLString;       // remote fallback / live source
@property(nonatomic, copy, nullable) NSString *destinationURLString; // trophies: subreddit/link the trophy points at

// Per-user runtime state (set by the scraper join; not part of the catalogue).
@property(nonatomic) BOOL earned;
// For a live trophy that isn't in the bundled catalogue, we still want to show it.
@property(nonatomic) BOOL isLiveUncatalogued;

// The bundled downscaled icon, decoded. BLOCKING: reads the file and forces an
// ImageIO decode when the cache is cold, so this must never be called from the
// main thread — use cachedBundledImage/loadBundledImage: there.
- (nullable UIImage *)bundledImage;
// Already-decoded icon, or nil if the cache is cold. Never touches disk, so it is
// safe from a cell/layout path on the main thread.
- (nullable UIImage *)cachedBundledImage;
// cachedBundledImage when warm (completion runs synchronously, before returning),
// else a background decode with the completion on the main queue. Called exactly
// once; the image is nil when the item has no bundled art or the file is missing.
- (void)loadBundledImage:(void (^)(UIImage *_Nullable image))completion;
@end

@interface ApolloBadgeBookCatalog : NSObject
+ (instancetype)shared;

// YES once the bundled catalogue JSON loaded successfully.
@property(nonatomic, readonly) BOOL isLoaded;

// Full catalogue in render order.
@property(nonatomic, readonly) NSArray<ApolloBadgeItem *> *achievements;    // grouped by category order below
@property(nonatomic, readonly) NSArray<ApolloBadgeItem *> *trophies;        // title order
@property(nonatomic, readonly) NSArray<NSString *> *achievementCategories;  // ordered category names

// Achievements that belong to a category, in catalogue order.
- (NSArray<ApolloBadgeItem *> *)achievementsInCategory:(NSString *)category;

// Lookup helpers used when joining scraped per-user data onto the catalogue.
- (nullable ApolloBadgeItem *)achievementWithIdentifier:(NSString *)identifier;
// Match a scraped image URL to a catalogue entry by its stable CDN basename
// (e.g. ".../mgol2ep2mnwd1.png"). Robust to markup changes.
- (nullable ApolloBadgeItem *)itemMatchingImageURL:(nullable NSString *)urlString;
// Match an API (RedditKit) trophy to a catalogue entry. The API serves
// redditstatic.com/awards2/<slug>-<size>.png icons while the catalogue images are
// i.redd.it/cms/<hash>_trophy_image_for_<slug>.png, so the join is by normalized
// slug (from the API icon URL) with the display title as fallback.
- (nullable ApolloBadgeItem *)trophyMatchingIconURL:(nullable NSString *)iconURLString
                                              title:(nullable NSString *)title;
@end

// Resolve the on-disk directory holding the bundled BadgeBook assets across every
// install layout (sim bundle, sideload deb, jailbreak rootful/rootless, IPA).
FOUNDATION_EXPORT NSString *_Nullable ApolloBadgeBookResourceDirectory(void);

// Decode every bundled icon into the image cache off the main thread, so the
// first scroll through the book (and the header strip) never decodes on main.
// One-shot; safe to call from anywhere.
FOUNDATION_EXPORT void ApolloBadgeBookPrewarmImages(void);

NS_ASSUME_NONNULL_END
