#import <Foundation/Foundation.h>

// Extracted from Apollo's Action enum title and icon switch tables.
// Regenerate from the binary if Apollo's actionKind values change.
static NSString *const kApolloNativeActionDefaultTitles[] = {
    @"Translate", @"Crosspost", @"", @"Upvote",
    @"Undo Upvote", @"Downvote", @"Undo Downvote", @"Save",
    @"Saved Category", @"All", @"Add Category", @"Unsave",
    @"Reply", @"Collapse", @"Collapse to Top", @"Share",
    @"Delete", @"Share as Image\u2026", @"Share Image Link", @"Share Album Link",
    @"Copy Album Link", @"Copy Text", @"Share Reddit Link", @"Share Comment Link",
    @"Share Message Link", @"Share Content Link", @"Save Image", @"Share Image",
    @"Share Video", @"Download Video\u2026", @"Download GIF\u2026", @"Save GIF",
    @"Share GIF", @"Share Link", @"Share Link", @"Share Text",
    @"Sidebar", @"View Moderators", @"Subscribe", @"Unsubscribe",
    @"Favorite", @"Unfavorite", @"Author", @"View All Replies",
    @"Subreddit", @"Parent Comment", @"Set User Flair", @"Set Flair",
    @"Subreddit Rules", @"Mark Spoiler", @"Unmark Spoiler", @"Submit Post",
    @"Subscription", @"Subreddit Group", @"Multireddit", @"Multireddit",
    @"Preview", @"Search", @"Superscript", @"Quote",
    @"List", @"Popular Posts", @"Home", @"All Posts",
    @"Strikethrough", @"Ordered List", @"Unordered List", @"Code",
    @"Horizontal Line", @"Header", @"Start Live Activity", @"End Live Activity",
    @"XXL Header", @"XL Header", @"L Header", @"ML Header",
    @"M Header", @"S Header", @"Hashtag", @"Sort by Total Comments",
    @"Sort by Hot", @"Sort by New", @"Sort by Rising", @"Sort by Controversial",
    @"Sort by Best", @"Sort by Old", @"Sort by Random", @"Sort by Top",
    @"Sort Live", @"Sort by Q&A", @"Sort by Relevance", @"Sort by Top (Hour)",
    @"Sort by Top (Day)", @"Sort by Top (Week)", @"Sort by Top (Month)", @"Sort by Top (6 Months)",
    @"Sort by Top (Year)", @"Sort by Top (All Time)", @"Select Text", @"Copy Link",
    @"Copy Image", @"Edit", @"Mark NSFW", @"Unmark NSFW",
    @"Text Faces", @"SpongeText", @"Subreddit Notifications", @"Custom Subreddit Watcher",
    @"Turn on Trending Posts", @"Turn Off Trending Posts", @"Open in Safari", @"In-App Safari",
    @"Safari", @"Open in Chrome", @"Open in Firefox", @"Open in Edge",
    @"Open in Dolphin", @"Open in YouTube", @"", @"View Post",
    @"Collapse Child Comments", @"Expand Child Comments", @"Give Award", @"Report",
    @"Moderator", @"Mark Spam", @"Approve", @"Reapprove",
    @"Remove", @"View Reports", @"Ignore Reports", @"Unignore Reports",
    @"Set Suggested Sort", @"Clear Suggested Sort", @"Enable Contest Mode", @"Disable Contest Mode",
    @"Distinguish", @"Undistinguish", @"Mark NSFW", @"Unmark NSFW",
    @"Mark Spoiler", @"Unmark Spoiler", @"Lock", @"Unlock",
    @"Set User Flair", @"Set Post Flair", @"Lock", @"Select Text",
    @"Translate", @"Share Text", @"Share Message Link", @"Share Comment Link",
    @"Unlock", @"Sticky", @"Unsticky", @"Ban User",
    @"Copy Link", @"Copy Text", @"Copy Image", @"Mute Modmail",
    @"Unmute Modmail", @"Comment Nuke", @"Get Compliment", @"Mod Queue",
    @"Mod Mail", @"Traffic Stats", @"Mod Log", @"Reports",
    @"Spam", @"Unmoderated", @"Ban Users", @"Mute Users",
    @"Edit Flair", @"Block User", @"Subreddit Settings", @"Rules",
    @"Edit Stylesheets", @"Moderators", @"Edited", @"Approved Submitters",
    @"Self", @"Private Mod Discussion", @"Send to User", @"Subreddit",
    @"Private Moderator Note", @"User Report Card", @"Report", @"Reply",
    @"Archive", @"Unarchive", @"Recent", @"Unread",
    @"Moderator", @"User", @"Relevance", @"New Modmail",
    @"Mark All Read", @"Highlight", @"Unhighlight", @"Author",
    @"Subreddit", @"Mark Read", @"All Posts", @"All Comments",
    @"View Post", @"View Comment", @"View Message", @"Share",
    @"Subreddits", @"Removal Reason", @"AutoModerator", @"",
    @"All Modmail", @"In Progress", @"Notifications", @"Mark Unread",
    @"Mark OC", @"Unmark OC", @"Moderator", @"Action",
    @"New", @"Include Subscriptions", @"Exclude Subscriptions", @"Mark Unread",
    @"Mark Read", @"Block User", @"Unblock User", @"Filter From r/All",
    @"Unfilter from r/All", @"Private Message", @"Add Friend", @"Remove Friend",
    @"Follow", @"Unfollow", @"Large Thumbnails", @"Compact Posts",
    @"Cropped", @"Zoomed Out", @"Full Height", @"Hide",
    @"Unhide", @"Hide Posts Above", @"Unhide Posts Above", @"Hide Read Posts",
    @"Left Top", @"Left Middle", @"Left Bottom", @"Center",
    @"Right Top", @"Right Middle", @"Right Bottom", @"Mute Notifications",
    @"Unmute Notifications", @"Brave", @"iCab", @"Firefox Focus",
    @"Tweetbot", @"Twitterrific", @"Twitter", @"Aviary",
    @"Spring"
};

static NSString *const kApolloNativeActionDefaultAssetNames[] = {
    @"option-translate", @"option-crosspost", @"option-remind-me-in", @"option-upvote",
    @"option-undo-upvote", @"option-downvote", @"option-undo-downvote", @"option-save",
    @"option-saved-category", @"option-clear", @"option-add", @"option-unsave",
    @"option-reply", @"option-collapse", @"option-collapse-to-top", @"option-share",
    @"option-trash", @"option-share-as-image", @"option-safari", @"option-link",
    @"option-link", @"option-copy", @"option-link", @"option-link",
    @"option-link", @"option-link", @"option-download", @"option-image",
    @"option-video", @"option-download", @"option-download", @"option-download",
    @"option-gif", @"option-link", @"option-link", @"option-text",
    @"option-sidebar", @"option-moderator", @"option-subscribe", @"option-unsubscribe",
    @"option-favorite", @"option-unfavorite", @"option-author", @"option-view-all-replies",
    @"option-subreddit", @"option-view-parent", @"option-set-flair", @"option-set-flair",
    @"option-rules", @"option-spoiler", @"option-spoiler", @"option-submit",
    @"option-subreddit", @"option-subreddit-group", @"option-multireddit", @"option-multireddit",
    @"option-preview", @"option-search", @"option-superscript", @"option-quote",
    @"option-list", @"option-popular", @"option-home", @"option-all-posts",
    @"option-strikethrough", @"option-ordered-list", @"option-unordered-list", @"option-code",
    @"option-horizontal-rule", @"option-header", @"option-live-activity", @"option-live-activity",
    @"option-h1", @"option-h2", @"option-h3", @"option-h4",
    @"option-h5", @"option-h6", @"option-hashtag", @"option-sort-comments",
    @"option-sort-hot", @"option-sort-new", @"option-sort-rising", @"option-sort-controversial",
    @"option-sort-best", @"option-sort-old", @"option-sort-random", @"option-sort-top",
    @"option-sort-live", @"option-sort-qa", @"option-sort-relevance", @"option-sort-hour",
    @"option-sort-day", @"option-sort-week", @"option-sort-month", @"option-sort-six-months",
    @"option-sort-year", @"option-sort-all-time", @"option-select-mode", @"option-copy",
    @"option-copy", @"option-edit", @"option-nsfw", @"option-nsfw",
    @"option-text-faces", @"option-spongetext", @"option-notifications", @"option-subreddit-watcher",
    @"option-trending-notifications", @"option-trending-notifications", @"option-safari", @"option-safari",
    @"option-safari", @"option-chrome", @"option-firefox", @"option-microsoft-edge",
    @"option-dolphin", @"option-youtube", @"option-more", @"option-posts",
    @"option-collapse-child-comments", @"option-expand-child-comments", @"option-gift-award", @"option-report",
    @"option-moderator", @"option-spam", @"option-approve", @"option-approve",
    @"option-trash", @"option-report", @"option-block", @"option-block",
    @"option-set-suggested-sort", @"option-clear", @"option-contest-mode", @"option-contest-mode",
    @"option-moderator", @"option-moderator", @"option-nsfw", @"option-nsfw",
    @"option-spoiler", @"option-spoiler", @"option-lock", @"option-lock",
    @"option-set-flair", @"option-set-flair", @"option-lock", @"option-select-mode",
    @"option-translate", @"option-text", @"option-link", @"option-link",
    @"option-lock", @"option-sticky", @"option-sticky", @"option-ban",
    @"option-copy", @"option-copy", @"option-copy", @"option-mute-modmail",
    @"option-mute-modmail", @"option-comment-nuke", @"option-congratulate-self", @"option-mod-queue",
    @"option-mail", @"option-traffic-stats", @"option-mod-log", @"option-report",
    @"option-spam", @"option-hide", @"option-ban", @"option-mute-modmail",
    @"option-set-flair", @"option-block", @"option-spanner", @"option-rules",
    @"option-css", @"option-moderator", @"option-edit", @"option-approved-submitters",
    @"option-author", @"option-moderator", @"option-author", @"option-subreddit",
    @"option-private-moderator-note", @"option-report-card", @"option-report", @"option-reply",
    @"option-archive", @"option-archive", @"option-sort-new", @"option-sort-unread",
    @"option-moderator", @"option-author", @"option-sort-relevance", @"option-submit",
    @"option-mark-all-read", @"option-highlight", @"option-highlight", @"option-author",
    @"option-subreddit", @"option-mark-read", @"option-posts", @"option-comments",
    @"option-post", @"option-comments", @"option-mail", @"option-share",
    @"option-subreddit", @"option-removal-reason", @"option-automoderator", @"option-more",
    @"option-private-message", @"option-in-progress", @"option-modmail-notifications", @"option-mark-unread",
    @"option-original-content", @"option-original-content", @"option-author", @"option-moderator",
    @"option-sort-new", @"option-include-subscriptions", @"option-exclude-subscriptions", @"option-mark-unread",
    @"option-mark-read", @"option-block", @"option-block", @"option-block",
    @"option-unblock", @"option-private-message", @"option-add-friend", @"option-remove-friend",
    @"option-follow", @"option-unfollow", @"option-large-thumbnails", @"option-compact-thumbnails-right",
    @"option-comments-header-cropped", @"option-comments-header-zoomed-out", @"option-comments-header-full-height", @"option-hide",
    @"option-unhide", @"option-hide-all-above", @"option-unhide-all-above", @"option-hide-read",
    @"option-jump-button-left-top", @"option-jump-button-left-middle", @"option-jump-button-left-bottom", @"option-jump-button-center",
    @"option-jump-button-right-top", @"option-jump-button-right-middle", @"option-jump-button-right-bottom", @"option-mute-notifications",
    @"option-unmute-notifications", @"option-brave", @"option-icab", @"option-firefox",
    @"option-tweetbot", @"option-twitterrific", @"option-twitter", @"option-aviary",
    @"option-spring-twitter"
};
